### ISSUE TITLE
Importing modules

### ISSUE THREAD

**Issue by NickRoss** [dsi-clinic/cocoa#30]
@ridhi96 reports that the output is saying that there are missing modules. Can we get a working reproducible example to fix and diagnose?

**Comment by NickRoss** [comment]
These are from IE Project

![Picture2](https://github.com/dsi-clinic/cocoa/assets/1413736/b32474fa-1b81-4c31-8f4a-e1af96ea97dd)
![Picture1](https://github.com/dsi-clinic/cocoa/assets/1413736/45c7dc0b-d4e6-4ff0-baed-196a0deb9c68)

**Comment by timhannifan** [comment]
There were 2 issues here:
1) False Pylint warnings for import-error (E0401). Since we are running pylint outside of the environment the repository uses, we get pylint warnings for every package that cannot be found. This is incorrect. I resolved the issue by ignoring this type of error in the reported warnings.
2) True Pylint warnings for no-name-in-module (E0611). I was able to resolve this by using a different style of import path for the local modules. For example in utils/processing.py, rather than `from utils import abs_fixed_avail`, use `from utils.utils import abs_fixed_avail`.
